"""Chapters 12 and 13: structural mapping and metadata."""

from peaa.authoring.model import Section

ST = "peaa/lab/patterns/or_structural.py"
META = "peaa/lab/patterns/or_metadata.py"


def _s(**kwargs) -> Section:
    return Section(**kwargs)


def sections() -> list[Section]:
    return [
        _s(
            id="ch12-or-structural",
            nav="Ch.12 OR structure",
            group="الجزء ٢ · هيكل الربط",
            title="Object-Relational Structural Patterns",
            subtitle="المفتاح، العلاقات، القيمة المركبة، ووراثة الجداول",
            icon="🧱",
            tone="amber",
            intent="شكل الربط: فين المفتاح، إزاي المفتاح الأجنبي يبقى مرجعًا، إزاي جدول وسيط يربط مفتشين، إزاي البنود تتحفظ مع الأب، وإزاي شاحنة ورافعة يتشاركوا جدولًا أو ينفصلوا.",
            use=["تصميم جداول تطابق نموذج الأصول.", "اختيار استراتيجية وراثة قبل ما البيانات تكبر."],
            avoid=["ثلاث استراتيجيات وراثة في نفس المشروع من غير سبب.", "حفظ كائن متداخل بزرّ أعمدة يدوي في كل شاشة."],
            diagram="keys → associations → dependent lines → Money columns → inheritance",
            relations=[("Identity Field", "pattern-identity-field"), ("Foreign Key Mapping", "pattern-foreign-key-mapping"), ("Single Table Inheritance", "pattern-single-table-inheritance")],
            lab=ST, demo="foreign_key_mapping",
            snippet="lease.customer.name  # joined from customers",
            tasks=["ارسم المفاتيح بين leases و customers و lease_lines.", "اختَر STI أو CTI لنوع أصل جديد واكتب السبب."],
            questions=[
                ("الفصل عن سلوك التحميل؟", "لا. السلوك في ١١. هنا شكل البيانات."),
                ("Embedded Value مثاله في القصة؟", "المبلغ كسنت وعملة على الفاتورة."),
                ("Dependent Mapping للبنود ليه؟", "البند ما يعيشش من غير عقد."),
                ("Inheritance Mappers بتيجي بعد إيه؟", "بعد ما تختار شكل جداول الوراثة، المابر يوجّه التحميل."),
            ],
        ),
        _s(id="pattern-identity-field", nav="Identity Field", group="الجزء ٢ · هيكل الربط", title="Identity Field", subtitle="مفتاح الصف يعيش على الكائن", icon="🔑", tone="amber",
           intent="كل Lease في الذاكرة يحمل id يساوي المفتاح الأساسي. من غيره ما تقدرش تحدث الصف الصح ولا تبني Identity Map.",
           use=["أي كائن له صف.", "توليد مفتاح قبل الإدراج أو بعده بوضوح."],
           avoid=["الاعتماد على اسم العميل كمفتاح.", "خلط مفتاح القاعدة مع مفتاح واجهة مؤقت من غير تحويل."],
           diagram="DomainLease.id  ==  leases.id",
           relations=[("Identity Map", "pattern-identity-map"), ("Data Mapper", "pattern-data-mapper")],
           lab=ST, demo="identity_field",
           snippet="lease = Identified(id=row['id'])",
           tasks=["اطبع id قبل الحفظ وبعده لو أضفت عقدًا جديدًا.", "ارفض كائنين بنفس id في خريطة واحدة.", "اشرح مفتاحًا مركّبًا لو البند يتحدد بالعقد والأصل."],
           questions=[("الحقل ده سلوك عمل؟", "لا. هوية تخزين."), ("ينفع يكون None؟", "قبل الإدراج نعم، وبعدها لازم قيمة."), ("ليه مش الاسم؟", "الاسم يتغير ويتكرر."), ("علاقته بالخريطة؟", "الخريطة مفهرسة به.")]),
        _s(id="pattern-foreign-key-mapping", nav="Foreign Key Mapping", group="الجزء ٢ · هيكل الربط", title="Foreign Key Mapping", subtitle="customer_id يبقى كائن عميل", icon="🔗", tone="amber",
           intent="العمود customer_id في العقد يتحول إلى مرجع Customer فيه الاسم. الاتجاه من المفتاح الأجنبي إلى كائن، مش مجرد رقم في الواجهة.",
           use=["علاقة كثير-لواحد زي عقد لعميل.", "تحميل العميل مع العقد أو عند اللمس."],
           avoid=["تكرار اسم العميل في كل شاشة بدل المرجع.", "سلسلة مفاتيح أجنبية عبر شبكة."],
           diagram="leases.customer_id → customers.id → Customer(name)",
           relations=[("Association Table Mapping", "pattern-association-table-mapping"), ("Identity Field", "pattern-identity-field")],
           lab=ST, demo="foreign_key_mapping",
           snippet="LeaseWithCustomer(row['lease_id'], CustomerRef(row['customer_id'], row['name']))",
           tasks=["ارسم السهم من عقد نورة إلى العميل.", "حمّل العقد من غير اسم ثم أضف تحميلًا كسولًا للعميل.", "أضف أصلًا على البند بنفس النمط."],
           questions=[("العمود ولا الكائن؟", "العمود في الجدول، والكائن في الذاكرة."), ("كثير-لواحد ولا كثير-لكثير؟", "كثير عقود لعميل واحد. الكثير-لكثير يحتاج جدول ربط."), ("المعمل يطبع مين؟", "نورة."), ("لو العميل اتمسح؟", "مفتاح يتيم. عالجها بقيد أو Special Case.")]),
        _s(id="pattern-association-table-mapping", nav="Association Table", group="الجزء ٢ · هيكل الربط", title="Association Table Mapping", subtitle="مفتشون كثير لعقد كثير عبر جدول وسيط", icon="🪢", tone="amber",
           intent="لو العقد له عدة مفتشين والمفتش له عدة عقود، الجدول الوسيط lease_inspectors يحمل المفتاحين. المابر يبني المجموعة من غير أعمدة مكررة على الأب.",
           use=["علاقة كثير-لكثير حقيقية.", "الرابط نفسه من غير بيانات زيادة، أو مع بيانات بسيطة."],
           avoid=["جدول وسيط والبند فيه كمية وسعر؛ ده غالبًا كيان Dependent مش مجرد رابط.", "محاكاة الكثير-لكثير بسلسلة نصية من المعرفات."],
           diagram="leases *—* inspectors\n      lease_inspectors",
           relations=[("Foreign Key Mapping", "pattern-foreign-key-mapping"), ("Dependent Mapping", "pattern-dependent-mapping")],
           lab=ST, demo="association_table_mapping",
           snippet="SELECT i.name FROM lease_inspectors li JOIN inspectors i ...",
           tasks=["أضف مفتشًا ثالثًا على العقد ١.", "أزل الرابط من غير ما تحذف المفتش.", "اكتب ليه بنود الإيجار مش هذا النمط."],
           questions=[("الجدول الوسيط فيه إيه؟", "مفتاح العقد ومفتاح المفتش."), ("فرقه عن البنود؟", "البند كيان تابع بكمية. الرابط هنا عضوية."), ("لو الرابط له تاريخ؟", "ممكن يبقى كيان مستقل مش مجرد ربط."), ("المعمل يرجّع مين؟", "Lina و Omar.")]),
        _s(id="pattern-dependent-mapping", nav="Dependent Mapping", group="الجزء ٢ · هيكل الربط", title="Dependent Mapping", subtitle="البنود تتحفظ وتُمسح مع العقد", icon="📎", tone="amber",
           intent="بند الإيجار ما لهوش حياة مستقلة. لما تحفظ العقد، المابر يمسح البنود القديمة ويكتب المجموعة الحالية. الأب هو حدود الحفظ.",
           use=["أجزاء تركيبية تُحمَّل دائمًا مع الأب.", "استبدال مجموعة البنود دفعة واحدة."],
           avoid=["بند يشار إليه من مكان آخر.", "جدول ضخم تمسحه بالكامل كل حفظ صغير."],
           diagram="save(Lease):\n  DELETE lines WHERE lease_id\n  INSERT current lines",
           relations=[("Association Table Mapping", "pattern-association-table-mapping"), ("Unit of Work", "pattern-unit-of-work")],
           lab=ST, demo="dependent_mapping",
           snippet="""
DELETE FROM lease_lines WHERE lease_id = ?
INSERT each line of the lease graph
            """,
           tasks=["غيّر كمية الرافعة واحفظ العقد كبيان واحد.", "أثبت إن بندًا قديمًا اختفى بعد الحفظ.", "ارفض استخدام النمط لو فاتورة تشير لبند."],
           questions=[("ليه DELETE ثم INSERT؟", "عشان المجموعة في الذاكرة هي المصدر، مش فرق أعمدة متفرق."), ("البند له هوية مستقلة؟", "ممكن رقم داخل الأب، لكنه ما يُحمَّلش لوحده كجذر."), ("خطر المسح الكامل؟", "لو الجدول كبير أو فيه قفل، الفرق أدق."), ("مجموع الكميات في المعمل؟", "1+3 = 4 بعد إعادة الكتابة.")]),
        _s(id="pattern-embedded-value", nav="Embedded Value", group="الجزء ٢ · هيكل الربط", title="Embedded Value", subtitle="Money عمودان وكائن واحد", icon="💵", tone="amber",
           intent="القيمة المركبة الصغيرة، زي المبلغ والعملة، تتخزن كأعمدة في صف المالك وتتحول إلى Money. مش صف مستقل لأنها ما تتشاركش.",
           use=["Money، مدى تاريخ، أو عنوان مملوك لصف واحد.", "مساواة بالقيمة مش بالمرجع."],
           avoid=["كيان له حياة وارتباطات. ده جدول مش قيمة مضمّنة.", "عملة مختلفة تتجمع من غير فحص."],
           diagram="invoices.amount_cents + currency → Money",
           relations=[("Money", "pattern-money"), ("Value Object", "pattern-value-object"), ("Serialized LOB", "pattern-serialized-lob")],
           lab=ST, demo="embedded_value",
           snippet="Money(row['amount_cents'], row['currency'])",
           tasks=["أضف عمود عملة على بند واقرأه كـ Money.", "ارفض جمع USD مع عملة تانية في الكائن.", "قارن هذا بتخزين JSON للمبلغ."],
           questions=[("ليه مش جدول monies؟", "القيمة ما تتشاركش بين فواتير؛ هي جزء من الصف."), ("فرقه عن Serialized LOB؟", "الأعمدة قابلة للاستعلام. الـ LOB كتلة."), ("المعمل يطبع إيه؟", "USD 900.00."), ("ينفع null؟", "لو الفاتورة دايمًا بمبلغ، لأ. لو اختياري اجعل القيمة اختيارية بوضوح.")]),
        _s(id="pattern-serialized-lob", nav="Serialized LOB", group="الجزء ٢ · هيكل الربط", title="Serialized LOB", subtitle="شروط العقد كتلة JSON في عمود", icon="📄", tone="amber",
           intent="جزء من الكائن معقّد ونادر ما تبحث داخله: شروط الإرجاع. خزنه كتلة في عمود نصي أو ثنائي وأعد بناءه عند التحميل. المعمل يستخدم JSON مش تنسيق غامض.",
           use=["مستند صغير مملوك للصف وبلا استعلامات داخلية.", "شكل يتغير أسرع من المخطط."],
           avoid=["حقل هتعمل عليه WHERE كتير.", "تنسيق ما تقدرش تقرأه بعد سنة."],
           diagram="terms dict ↔ leases.terms_json",
           relations=[("Embedded Value", "pattern-embedded-value"), ("Dependent Mapping", "pattern-dependent-mapping")],
           lab=ST, demo="serialized_lob",
           snippet="""
terms = json.loads(raw)
terms["grace_days"] = 5
save(json.dumps(terms))
            """,
           tasks=["أضف حقل شرط واقرأه بعد الحفظ.", "اكتب استعلامًا تعجز عنه بسبب الـ JSON واقترح عمودًا بدلًا منه.", "قارن JSON بأعمدة Embedded Value."],
           questions=[("LOB يعني إيه هنا؟", "Large Object: كتلة في عمود."), ("ليه JSON في المعمل؟", "عشان يتقرأ ويتفحص من غير ما يكون تنفيذًا خاصًا."), ("إمتى تطلّع الحقل لعمود؟", "لما تحتاج فهرس أو تقرير عليه."), ("المعمل يضيف إيه؟", "grace_days = 5 مع شرط الإرجاع.")]),
        _s(id="pattern-single-table-inheritance", nav="Single Table Inheritance", group="الجزء ٢ · هيكل الربط", title="Single Table Inheritance", subtitle="شاحنة ورافعة في جدول assets", icon="🧬", tone="amber",
           intent="كل أنواع الأصل في جدول واحد، وعمود kind يميّز. أعمدة الشاحنة فاضية في صف الرافعة والعكس. استعلام القائمة سهل، والجدول فيه فراغات.",
           use=["أنواع قليلة وأعمدة مشتركة كتير.", "تقارير على كل الأصول من غير UNION."],
           avoid=["عشرات الأعمدة الخاصة بكل نوع.", "قيود NOT NULL على حقل يخص نوعًا واحدًا."],
           diagram="assets(kind, axle_count, lift_height_cm)\ntruck uses axles · forklift uses lift",
           relations=[("Class Table Inheritance", "pattern-class-table-inheritance"), ("Concrete Table Inheritance", "pattern-concrete-table-inheritance"), ("Inheritance Mappers", "pattern-inheritance-mappers")],
           lab=ST, demo="single_table_inheritance",
           snippet="if row['kind'] == 'truck': data['axles'] = row['axle_count']",
           tasks=["أضف نوع مقطورة وعمودًا واحدًا ولاحظ الفراغ في باقي الصفوف.", "اكتب قيدًا يمنع axle على رافعة.", "قارن استعلام كل الأصول مع CTI."],
           questions=[("المميّز فين؟", "عمود kind."), ("عيب الفراغ؟", "أعمدة بلا معنى لبعض الصفوف."), ("ميزة التقرير؟", "جدول واحد من غير دمج."), ("المعمل يفرّق النوع إزاي؟", "axles للشاحنة و lift للرافعة.")]),
        _s(id="pattern-class-table-inheritance", nav="Class Table Inheritance", group="الجزء ٢ · هيكل الربط", title="Class Table Inheritance", subtitle="جدول أساس وجداول للأبناء", icon="🧬", tone="amber",
           intent="البيانات المشتركة في asset_base، والمحاور في trucks، وارتفاع الرفع في forklifts. كل نوع نظيف، والتحميل يحتاج ربطًا.",
           use=["حقول خاصة كثيرة لكل نوع.", "عايز قيود واضحة على جدول الابن."],
           avoid=["أنواع كتير والوصلات بتبطئ كل قراءة.", "تقرير بسيط كان STI يكفيه."],
           diagram="asset_base 1—1 trucks\nasset_base 1—1 forklifts",
           relations=[("Single Table Inheritance", "pattern-single-table-inheritance"), ("Concrete Table Inheritance", "pattern-concrete-table-inheritance")],
           lab=ST, demo="class_table_inheritance",
           snippet="SELECT b.name, t.axle_count FROM asset_base b JOIN trucks t ON t.id = b.id",
           tasks=["أضف جدول ابن ثالث واربطه بالأساس بنفس المفتاح.", "اكتب تحميل رافعة من غير أعمدة شاحنة.", "عدّ الجداول اللازمة لتقرير كل الأسماء."],
           questions=[("المفتاح في الابن؟", "نفس مفتاح الأساس غالبًا."), ("الثمن؟", "JOIN عند التحميل."), ("المكسب؟", "ما فيش أعمدة فارغة بلا معنى."), ("المعمل يقرأ إيه؟", "Flatbed وعدد المحاور 3.")]),
        _s(id="pattern-concrete-table-inheritance", nav="Concrete Table Inheritance", group="الجزء ٢ · هيكل الربط", title="Concrete Table Inheritance", subtitle="جدول كامل لكل نوع أصل", icon="🧬", tone="amber",
           intent="truck_assets يحمل كل أعمدة الشاحنة، و forklift_assets كل أعمدة الرافعة. مفيش جدول أب. كل استعلام نوع مباشر، وتقرير الكل يحتاج UNION والحقول المشتركة تتكرر في المخطط.",
           use=["أنواع مستقلة تقريبًا ونادرًا ما تُستعلم معًا.", "تجنب وصلات CTI."],
           avoid=["حقل مشترك هيتغير اسمه في كل الجداول.", "هوية لازم تكون فريدة عبر كل الأنواع من غير تنسيق."],
           diagram="truck_assets (full columns)\nforklift_assets (full columns)\nno shared table",
           relations=[("Class Table Inheritance", "pattern-class-table-inheritance"), ("Inheritance Mappers", "pattern-inheritance-mappers")],
           lab=ST, demo="concrete_table_inheritance",
           snippet="SELECT name, axle_count FROM truck_assets",
           tasks=["اكتب UNION للأسماء من الجدولين.", "أضف عمود عملة في الاثنين ولاحظ التكرار.", "قارن إدراج شاحنة مع STI."],
           questions=[("فين الأعمدة المشتركة؟", "مكررة في كل جدول ملموس."), ("ليه من غير JOIN للنوع؟", "كل أعمدة الشاحنة في جدولها."), ("صعوبة التقرير؟", "تدمج الجداول بنفسك."), ("المعمل يقرأ من أنهي جدول؟", "truck_assets.")]),
        _s(id="pattern-inheritance-mappers", nav="Inheritance Mappers", group="الجزء ٢ · هيكل الربط", title="Inheritance Mappers", subtitle="مابر يوجّه التحميل حسب النوع", icon="🧭", tone="amber",
           intent="بعد اختيار شكل الجداول، طبقة المابر تعكس الوراثة: AssetMapper يقرأ المميّز ويستدعي TruckMapper أو ForkliftMapper. الكود اللي فوق يطلب أصلًا من غير ما يعرف الجدول.",
           use=["أي استراتيجية وراثة فوقها دومين فيه أب وأبناء.", "عزل SQL الخاص بكل نوع."],
           avoid=["مابر وراثة فوق سكربت ما فيهوش أنواع.", "منطق سعر داخل المابر بدل كائن الأصل."],
           diagram="AssetMapper.load → kind → TruckMapper | ForkliftMapper",
           relations=[("Single Table Inheritance", "pattern-single-table-inheritance"), ("Data Mapper", "pattern-data-mapper")],
           lab=ST, demo="inheritance_mappers",
           snippet="return self._by_kind[kind].load(conn, asset_id)",
           tasks=["أضف نوعًا وسجّله في القاموس.", "خلّي كل مابر ابن يبني كائن دومين مش قاموس فقط.", "اربط الشكل بـ STI الحالي في جدول assets."],
           questions=[("المابر الأب بيعمل إيه؟", "يختار المابر الابن حسب النوع."), ("فين SQL الأعمدة الخاصة؟", "في مابر الابن."), ("ينفع مع CTI؟", "نعم، الابن يعمل JOIN المناسب."), ("المعمل يرجّع إيه للرافعة؟", "type forklift وارتفاع الرفع.")]),
        _s(
            id="ch13-or-metadata",
            nav="Ch.13 Metadata",
            group="الجزء ٢ · ميتاداتا",
            title="Object-Relational Metadata Mapping Patterns",
            subtitle="وصف الحقول، استعلام مركّب، ومجموعة عقود",
            icon="🗂️",
            tone="teal",
            intent="بدل تكرار خريطة الأعمدة في كل مابر، صفها كبيانات. Query Object يبني الشرط من غير ما يلصق SQL في الواجهة. Repository يقدّم العقود كمجموعة: هات النشط، هات هذا.",
            use=["مابرات كتير بنفس شكل الترجمة.", "واجهة دومين ما تحبش تشوف WHERE."],
            avoid=["إطار ميتاداتا قبل تالت مابر مكتوب يدويًا.", "مستودع يسرّب جملة SQL للمتصل."],
            diagram="metadata → mapper\ncriteria → Query Object → SQL\nRepository.active()",
            relations=[("Metadata Mapping", "pattern-metadata-mapping"), ("Query Object", "pattern-query-object"), ("Repository", "pattern-repository")],
            lab=META, demo="repository",
            snippet="LeaseRepository(conn).active()",
            tasks=["صف حقول العقد كقاموس وحمّل صفًا منه.", "ابنِ استعلام حالة من Query Object."],
            questions=[
                ("الميتاداتا بديل للمابر؟", "لا. بتغذّي مابرًا عامًا."),
                ("Query Object بيحمي من إيه؟", "من لصق شروط عشوائية، لو الأعمدة المسموحة محدودة."),
                ("Repository يشبه إيه؟", "مجموعة في الذاكرة: أضف، هات، ابحث بمعايير دومين."),
                ("الثلاثة لازم مع بعض؟", "لا. كل واحد يحل تكرارًا مختلفًا."),
            ],
        ),
        _s(id="pattern-metadata-mapping", nav="Metadata Mapping", group="الجزء ٢ · ميتاداتا", title="Metadata Mapping", subtitle="قاموس الحقول يقود التحميل", icon="🧾", tone="teal",
           intent="LEASE_META يقول اسم الجدول وربط الصفة بالعمود. MetaMapper عام يقرأ الوصف. إضافة حقل تعديل بيانات مش كود تحميل جديد.",
           use=["جداول كثيرة بنفس إيقاع القراءة.", "عايز تولّد جزء من المابر."],
           avoid=["وصف يخبي استثناءات معقّدة أحسن تبان في كود.", "ميتاداتا من مدخل مستخدم من غير قيد."],
           diagram="fields: id→id, status→status\nMetaMapper.find uses the map",
           relations=[("Data Mapper", "pattern-data-mapper"), ("Query Object", "pattern-query-object")],
           lab=META, demo="metadata_mapping",
           snippet="return {attr: row[column] for attr, column in meta['fields'].items()}",
           tasks=["أضف status إلى وصف جدول آخر وأعد استخدام المابر.", "ارفض اسم جدول مش في قائمة بيضاء.", "اكتب فرقًا عن مابر يدوي."],
           questions=[("إيه اللي بيتخزن في الوصف؟", "جدول وربط صفات بأعمدة."), ("الكود العام بيعمل إيه؟", "يبني SELECT من الوصف."), ("خطر الوصف الديناميكي؟", "حقن أو عمود غلط لو المدخل حر."), ("المعمل يرجّع إيه؟", "id و customer_id و status للعقد 1.")]),
        _s(id="pattern-query-object", nav="Query Object", group="الجزء ٢ · ميتاداتا", title="Query Object", subtitle="شرط في كائن يتحول إلى SQL", icon="🔎", tone="teal",
           intent="بدل ما الواجهة تلصق WHERE، تبني Query.eq('status','active'). الكائن يولّد SQL ومعاملات. الأعمدة المسموحة محدودة في المعمل.",
           use=["بحث يتركب وقت التشغيل.", "عزل صياغة SQL عن الشاشة."],
           avoid=["تمرير اسم عمود من المستخدم من غير قائمة.", "استعلام معقّد أنضف وهو SQL واضح في بوابة."],
           diagram="Query('leases').eq('status','active') → SELECT ... WHERE status = ?",
           relations=[("Repository", "pattern-repository"), ("Metadata Mapping", "pattern-metadata-mapping")],
           lab=META, demo="query_object",
           snippet="""
sql, params = Query("leases").eq("status", "active").sql()
rows = conn.execute(sql, params)
            """,
           tasks=["أضف شرط customer_id وركّبه مع الحالة.", "ارفض عمودًا خارج القائمة.", "خلّي Repository يستدعي Query داخليًا."],
           questions=[("ليهه معاملات مش لصق نص؟", "عشان القيمة ما تغيّرش شكل الاستعلام."), ("القائمة البيضاء ليه؟", "اسم العمود ما يتأمنش بعلامة الاستفهام."), ("فرقه عن Repository؟", "الاستعلام آلية. المستودع لغة الدومين."), ("ناتج المعمل؟", "العقد 1 النشط.")]),
        _s(id="pattern-repository", nav="Repository", group="الجزء ٢ · ميتاداتا", title="Repository", subtitle="العقود مجموعة: هات النشط", icon="📚", tone="teal",
           intent="المستدعي يقول هات العقود النشطة أو هات هذا العقد. المستودع يخبي SQL. الدومين يتكلم مجموعة مش جداول.",
           use=["واجهة دومين فوق المابر.", "اختبار بمنفّذ ذاكرة لاحقًا."],
           avoid=["دالة مستودع لكل زرار في الواجهة.", "إرجاع Row للواجهة."],
           diagram="repo.active() / repo.get(1)\ninside: SQL or mapper",
           relations=[("Query Object", "pattern-query-object"), ("Data Mapper", "pattern-data-mapper"), ("Service Layer", "pattern-service-layer")],
           lab=META, demo="repository",
           snippet="""
class LeaseRepository:
    def active(self):
        return rows_where_status_active()
            """,
           tasks=["أضف overdue بمعيار دومين حتى لو المعمل يفلتر الحالة فقط.", "استبدل الجسم ببيانات في الذاكرة في اختبار.", "خلّي الخدمة تعتمد على المستودع مش على conn."],
           questions=[("المستودع مابر؟", "لا. واجهة مجموعة. المابر أداة جواه."), ("ليهه مش في الواجهة؟", "عشان الشاشة ما تعرفش الجداول."), ("إيه active في المعمل؟", "عقد 1."), ("علاقته بـ Query Object؟", "بحث معقّد يتبني كاستعلام داخل المستودع.")]),
    ]
