"""Chapters 14–18: web, distribution, offline locks, session, base."""

from peaa.authoring.model import Section

WEB = "peaa/lab/patterns/web_presentation.py"
DIST = "peaa/lab/patterns/distribution.py"
OFF = "peaa/lab/patterns/offline_concurrency.py"
SESS = "peaa/lab/patterns/session_state.py"
BASE = "peaa/lab/patterns/base_patterns.py"


def _s(**kwargs) -> Section:
    return Section(**kwargs)


def sections() -> list[Section]:
    return [
        _s(id="ch14-web", nav="Ch.14 Web patterns", group="الجزء ٢ · الويب", title="Web Presentation Patterns", subtitle="من MVC إلى معالج الخطوات", icon="🌐", tone="amber",
           intent="مرجع عرض الويب: تقسيم النموذج والعرض والكنترولر، ثم نقطة الدخول، ثم شكل العرض، ثم مسار المعالج.",
           use=["تصميم طلب HTTP حول عقد الإيجار.", "اختيار قالب مقابل JSON."],
           avoid=["منطق القسط في أي نمط عرض.", "كل الأنماط مرة واحدة في صفحة ثابتة."],
           diagram="MVC\nPage | Front controller\nTemplate | Transform | Two Step\nApplication Controller",
           relations=[("MVC", "pattern-mvc"), ("Front Controller", "pattern-front-controller"), ("Application Controller", "pattern-application-controller")],
           lab=WEB, demo="mvc", snippet="return view(model)",
           tasks=["اتبع طلب عرض من الكنترولر للقالب.", "حوّل نفس النموذج بـ Transform View."],
           questions=[("الأنماط دي فين من الطبقات؟", "في العرض، والنموذج تحتها."), ("Application Controller فرقه؟", "بيحكم انتقال الخطوات مش رسم الصفحة."), ("Two Step View ليه خطوتين؟", "نموذج منطقي ثم رسم حسب الوسيط."), ("ينفع من غير إطار؟", "أيوه. المعامل دوال بايثون.")]),
        _s(id="pattern-mvc", nav="MVC", group="الجزء ٢ · الويب", title="Model View Controller", subtitle="النموذج يعرض عبر كنترولر", icon="🔺", tone="amber",
           intent="Model حالة العقد، View نص أو HTML، Controller يختار الفعل. الفصل يخلي نفس العقد يطلع لشاشة أو لنداء بعيد.",
           use=["أي واجهة تفاعلية فوق الدومين.", "أكتر من عرض لنفس النموذج."],
           avoid=["كنترولر يحسب القسط.", "نموذج يستورد قالب HTML."],
           diagram="action → controller → model → view",
           relations=[("Page Controller", "pattern-page-controller"), ("Template View", "pattern-template-view"), ("Domain Model", "pattern-domain-model")],
           lab=WEB, demo="mvc",
           snippet="""
def controller(action):
    if action == "show":
        return view(model)
            """,
           tasks=["أضف فعل bill يرجع نصًا مختلفًا من غير ما يغيّر شكل Lease.", "اكتب عرضًا ثانيًا لنفس القاموس.", "امنع SQL داخل view."],
           questions=[("مين يمتلك القواعد؟", "النموذج."), ("دور الكنترولر؟", "يفسّر الطلب ويختار العرض."), ("المعمل يطبع إيه؟", "Lease #1 is active."), ("MVC يفرض إطار ويب؟", "لا.")]),
        _s(id="pattern-page-controller", nav="Page Controller", group="الجزء ٢ · الويب", title="Page Controller", subtitle="دالة لكل صفحة", icon="📄", tone="amber",
           intent="كل صفحة أو فعل لها دالة: عرض العقد لوحده. بسيط وواضح لما الصفحات قليلة وما فيش معالجة مشتركة ضخمة للطلبات.",
           use=["صفحات مستقلة.", "تطبيق صغير العدد في المسارات."],
           avoid=["تكرار التحقق والمصادقة في كل دالة.", "توجيه معقّد أنسب له Front Controller."],
           diagram="show_lease_page() → HTML fragment",
           relations=[("Front Controller", "pattern-front-controller"), ("MVC", "pattern-mvc")],
           lab=WEB, demo="page_controller",
           snippet="def show_lease_page():\n    return f\"<page>lease {lease['id']}</page>\"",
           tasks=["أضف صفحة فاتورة بدالة جديدة.", "استخرج ترويسة مشتركة لو التكرار ظهر.", "قارن عدد نقاط الدخول مع الكنترولر الأمامي."],
           questions=[("قد إيه عدد المداخل؟", "مدخل لكل صفحة."), ("الميزة؟", "تقرأ الصفحة من غير موجّه عام."), ("العيب؟", "تكرار البنية التحتية."), ("المعمل يرجّع إيه؟", "وسم صفحة فيه رقم 1.")]),
        _s(id="pattern-front-controller", nav="Front Controller", group="الجزء ٢ · الويب", title="Front Controller", subtitle="مدخل واحد يوجّه للـ handlers", icon="🚦", tone="amber",
           intent="كل الطلبات تدخل دالة أمامية تبحث في جدول المسارات وتنادي المعالج. المصادقة والتسجيل يلفّوا المكان الواحد.",
           use=["مسارات كثيرة وسلوك مشترك قبل المعالج.", "API فيه GET و POST."],
           avoid=["صفحة واحدة؛ الدالة الأمامية زيادة.", "جدول مسارات يخبي منطق الدومين."],
           diagram="front(path) → routes[path](request)",
           relations=[("Page Controller", "pattern-page-controller"), ("Application Controller", "pattern-application-controller")],
           lab=WEB, demo="front_controller",
           snippet="""
routes = {"GET /lease": show, "POST /lease/bill": bill}
return routes[path]({})
            """,
           tasks=["أضف مسار إرجاع.", "ارفض مسارًا مجهولًا برسالة واضحة.", "ضع فحص جلسة قبل المعالج مش داخله."],
           questions=[("فرقه عن Page Controller؟", "مدخل واحد مقابل مدخل لكل صفحة."), ("المعالج لسه موجود؟", "نعم. الأمامي يوجّه فقط."), ("المعمل ينادي كام مسار؟", "اتنين: عرض وفوترة."), ("فين القسط؟", "مش هنا. في النموذج أو الخدمة.")]),
        _s(id="pattern-template-view", nav="Template View", group="الجزء ٢ · الويب", title="Template View", subtitle="قالب فيه فراغات للنموذج", icon="🧩", tone="amber",
           intent="النص الثابت في القالب، والقيم من النموذج تعبّي الفراغات. المعمل يستخدم string.Template. القالب ما يحسبش.",
           use=["HTML أو بريد شكله ثابت.", "مصممون يعدّلون العرض بعيدًا عن الدومين."],
           avoid=["شرط عمل معقّد داخل القالب.", "قالب يفتح قاعدة."],
           diagram="Template('Lease $id ($status)') + model",
           relations=[("Transform View", "pattern-transform-view"), ("Two Step View", "pattern-two-step-view"), ("MVC", "pattern-mvc")],
           lab=WEB, demo="template_view",
           snippet="Template('Lease $id ($status)').substitute(id=1, status='active')",
           tasks=["أضف فراغ اسم العميل.", "انقل أي if خاص بالسعر إلى النموذج.", "اكتب نفس البيانات بقالب نصي آخر."],
           questions=[("مين يملأ الفراغ؟", "العرض، من بيانات جاهزة."), ("لو الحساب داخل القالب؟", "كسر للفصل. الحساب في النموذج."), ("المعمل ينتج إيه؟", "Lease 1 (active)."), ("فرقه عن Transform؟", "القالب هيكل جاهز. التحويل يبني مستندًا من البيانات.")]),
        _s(id="pattern-transform-view", nav="Transform View", group="الجزء ٢ · الويب", title="Transform View", subtitle="من صف العقد إلى مستند", icon="🔄", tone="amber",
           intent="دالة تحوّل نموذج العقد إلى قاموس أو JSON مناسب للمستهلك. مفيش قالب؛ الشكل يتبنى في الكود. مناسب لواجهة برمجية.",
           use=["JSON أو XML.", "شكل المخرجات برنامج مش صفحة."],
           avoid=["تحويل فيه خصم القسط.", "بناء HTML طويل بالسلاسل هنا والقالب أنسب."],
           diagram="lease row → {leaseId, state} → JSON",
           relations=[("Template View", "pattern-template-view"), ("DTO", "pattern-dto")],
           lab=WEB, demo="transform_view",
           snippet="return {'leaseId': row['id'], 'state': row['status']}",
           tasks=["أضف المبلغ للمستند بعد ما الخدمة تحسبه.", "اكتب محوّلًا ثانيًا XML نصيًا.", "قارن الحقول مع DTO."],
           questions=[("ليه الأسماء تتغير؟", "شكل السلك غير شكل الجدول."), ("ده DTO؟", "قريب. التحويل يصنع شكل النقل."), ("المعمل يطلع JSON بإيه؟", "leaseId و state."), ("ينفع مع MVC؟", "العرض هنا محوّل مش قالب.")]),
        _s(id="pattern-two-step-view", nav="Two Step View", group="الجزء ٢ · الويب", title="Two Step View", subtitle="شاشة منطقية ثم رسم نصي", icon="2️⃣", tone="amber",
           intent="الخطوة الأولى تبني وصفًا منطقيًا: عنوان وحقول. الخطوة التانية ترسمه نصًا أو HTML. لما تضيف وسيطًا تغيّر الخطوة التانية بس.",
           use=["أكتر من وسيط لنفس الشاشة.", "عايز تختبر التركيب المنطقي لوحده."],
           avoid=["وسيط واحد وهيكل بسيط؛ قالب واحد يكفي.", "حشر CSS في النموذج المنطقي."],
           diagram="lease → logical screen → render_text",
           relations=[("Template View", "pattern-template-view"), ("Transform View", "pattern-transform-view")],
           lab=WEB, demo="two_step_view",
           snippet="""
logical = {"title": "Lease 1", "fields": [("status", "active")]}
render_text(logical)
            """,
           tasks=["أضف راسم HTML لنفس الشاشة المنطقية.", "أضف حقل عميل في الخطوة الأولى فقط.", "اكتب اختبارًا على القاموس المنطقي."],
           questions=[("إيه الخطوتان؟", "تركيب منطقي ثم رسم."), ("المكسب؟", "وسيط جديد من غير إعادة معنى الشاشة."), ("الخطوة الأولى HTML؟", "لا. عنوان وحقول."), ("المعمل يطبع إيه؟", "عنوان العقد ثم status: active.")]),
        _s(id="pattern-application-controller", nav="Application Controller", group="الجزء ٢ · الويب", title="Application Controller", subtitle="خطوات إرجاع الأصل", icon="🗺️", tone="amber",
           intent="يعرف من الخطوة الحالية إيه التالية: بداية، اختيار أصل، تأكيد، انتهاء. كنترولر الصفحة يعرض، وده يحكم التدفق.",
           use=["معالج متعدد الخطوات.", "تدفق يتغير حسب نوع العقد."],
           avoid=["صفحة عرض واحدة.", "قواعد خصم داخل جدول التدفق."],
           diagram="start → choose_asset → confirm → done",
           relations=[("Front Controller", "pattern-front-controller"), ("Client Session State", "pattern-client-session-state")],
           lab=WEB, demo="application_controller",
           snippet="flow = {'start': 'choose_asset', 'choose_asset': 'confirm', 'confirm': 'done'}",
           tasks=["أضف فرعًا لو الإرجاع المبكر يحتاج خطوة غرامة.", "خزّن الخطوة في حالة جلسة.", "افصل رسم الصفحة عن اسم الخطوة التالية."],
           questions=[("فرقه عن Front Controller؟", "الأمامي يوجّه طلبًا. ده يوجّه عملية."), ("فين الحالة؟", "في جلسة أو حقول عميل."), ("المعمل يطبع المسار؟", "start حتى done."), ("ينفع تدفق لكل نوع أصل؟", "نعم، ده سبب وجوده.")]),
        _s(id="ch15-distribution", nav="Ch.15 Distribution", group="الجزء ٢ · التوزيع", title="Distribution Patterns", subtitle="واجهة خشنة وكائن نقل", icon="📡", tone="blue",
           intent="نمطان بس على الحدود: اجمع العملية، وانقل بيانات مسطّحة. الباقي يفضل محليًا.",
           use=["نداء بين عمليات حقيقي.", "تقليل الرحلات."],
           avoid=["توزيع كل كائن.", "بيان كسول على السلك."],
           diagram="Remote Facade → DTO",
           relations=[("Remote Facade", "pattern-remote-facade"), ("DTO", "pattern-dto"), ("Distribution", "ch07-distribution")],
           lab=DIST, demo="remote_facade", snippet="facade.bill_and_summarize(1)",
           tasks=["صمّم نداءً واحدًا بدل أربعة.", "ارسم إيه اللي ما يخرجش من العملية."],
           questions=[("ليه الفصل قصير؟", "لأن النصيحة الأساسية: لا توزّع إلا لسبب، وبعدين اخشّن الواجهة."), ("DTO فيه سلوك قسط؟", "لا."), ("Remote Facade محلي في المعمل؟", "الشكل محلي عشان يوضح الخشونة من غير شبكة."), ("علاقته بـ Service Layer؟", "الخدمة تنفّذ. الواجهة البعيدة تغلفها على الحدود.")]),
        _s(id="pattern-remote-facade", nav="Remote Facade", group="الجزء ٢ · التوزيع", title="Remote Facade", subtitle="bill_and_summarize مرة واحدة", icon="📞", tone="blue",
           intent="واجهة بعيدة بدوال قليلة كل واحدة تكمل عملية: فوتر وأعد الملخص. تمنع الثرثرة عبر الشبكة. المعمل يمثّل الحدود بنداء واحد حتى من غير HTTP.",
           use=["عميل بعيد يحتاج عملية كاملة.", "دمج عدة تحديثات محلية في رحلة."],
           avoid=["دالة بعيدة لكل getter.", "وضع القواعد داخل الواجهة بدل الخدمة."],
           diagram="client → bill_and_summarize → service + domain → summary",
           relations=[("DTO", "pattern-dto"), ("Service Layer", "pattern-service-layer"), ("Gateway", "pattern-gateway")],
           lab=DIST, demo="remote_facade",
           snippet="return LeaseSummary(lease_id, status, total.cents, total.currency)",
           tasks=["عدّ الرحلات قبل وبعد الواجهة.", "أضف عملية return_and_summarize.", "اكتب إيه اللي يفضل جوه العملية."],
           questions=[("خشنة يعني إيه؟", "عملية كاملة مش وصول لحقل."), ("ليهه مش شبكة في المعمل؟", "الدرس شكل الواجهة. الشبكة تكلفة إضافية."), ("ترجع بيان؟", "لا. ترجع ملخص."), ("لو النداء فشل بعد الفوترة؟", "تحتاج حدود معاملة واضحة. الواجهة ما تخبيش النص نصًا.")]),
        _s(id="pattern-dto", nav="DTO", group="الجزء ٢ · التوزيع", title="Data Transfer Object", subtitle="ملخص مسطّح من غير سلوك", icon="📦", tone="blue",
           intent="LeaseSummary يحمل معرفًا وحالة وسنت وعملة. يتسلسل بسهولة. مش Lease اللي يعرف monthly_total. كائن نقل فقط.",
           use=["عبور حد عملية أو طبقة عرض.", "تجميد شكل البيانات بين فريقين."],
           avoid=["دومين من غير سلوك يتسمى DTO بالخطأ جوه العملية من غير حد.", "منطق خصم على الـ DTO."],
           diagram="Lease graph  →  LeaseSummary(id, status, cents, currency)",
           relations=[("Remote Facade", "pattern-remote-facade"), ("Value Object", "pattern-value-object")],
           lab=DIST, demo="dto",
           snippet="@dataclass(frozen=True)\nclass LeaseSummary:\n    lease_id: int\n    amount_cents: int",
           tasks=["أضف اسم العميل للملخص من غير إضافة دالة حساب.", "تأكد إن المجموع اتحسب في الدومين قبل التعبئة.", "قارن الحقول مع صف leases."],
           questions=[("فيه سلوك؟", "لا."), ("فرقه عن Value Object؟", "القيمة مفهوم دومين زي Money. الـ DTO شكل نقل."), ("ليهه frozen في المعمل؟", "عشان النقل ما يتعدلش بالسكوت."), ("المبلغ فين اتحسب؟", "في Lease قبل بناء الملخص.")]),
        _s(id="ch16-offline", nav="Ch.16 Offline locks", group="الجزء ٢ · أقفال أوفلاين", title="Offline Concurrency Patterns", subtitle="أقفال بين جلسات، مش بين خيوط", icon="👥", tone="coral",
           intent="المستخدم يفتح العقد ويفكر. المعاملة القصيرة ما تغطيش الزمن ده. الأقفال هنا إصدار متفائل، قفل متشائم، قفل على الجذر، وقفل تخبيه البنية.",
           notes=["الخيوط والطوابير في الجزء ٣. لا تستخدم threading.Lock مكان version."],
           use=["تحرير نفس العقد من جلستين.", "حماية بيان مع بنوده."],
           avoid=["قفل من غير انتهاء.", "اعتبار القفل الأوفلاين حلًا لسباق عدّاد داخل العملية."],
           diagram="optimistic version | pessimistic owner | coarse root | implicit inside mapper",
           relations=[("Optimistic Offline Lock", "pattern-optimistic-offline-lock"), ("Pessimistic Offline Lock", "pattern-pessimistic-offline-lock"), ("Part 3", "part3-concurrency")],
           lab=OFF, demo="optimistic_offline_lock", snippet="UPDATE ... WHERE version = ?",
           tasks=["مثّل تعارض إصدار.", "اكتب جملة الفرق عن Monitor Object."],
           questions=[("أوفلاين يشير لإيه؟", "بين الطلبات، خارج المعاملة القصيرة."), ("متفائل ولا متشائم أولًا؟", "المتفائل لو التعارض نادر. المتشائم لو الفشل غالي."), ("Coarse-Grained على إيه؟", "على جذر العقد."), ("Implicit ليه؟", "عشان التطبيق ما ينساش القفل.")]),
        _s(id="pattern-optimistic-offline-lock", nav="Optimistic Offline Lock", group="الجزء ٢ · أقفال أوفلاين", title="Optimistic Offline Lock", subtitle="احفظ فقط لو الإصدار لسه هو", icon="✳️", tone="coral",
           intent="كل عقد له version. الحفظ يعمل UPDATE بشرط الإصدار المقروء ويزوّد الرقم. الجلسة التانية بنفس الرقم القديم تفشل وتعيد التحميل.",
           use=["تعارض نادر وتحب تتجنب انتظار القفل.", "ويب كثير المستخدمين على نفس السجل."],
           avoid=["لو التعارض شائع والمستخدم هيعيد المحاولة طول الوقت.", "نسيان إرسال الإصدار مع النموذج."],
           diagram="read v0 · A writes v1 · B with v0 → Conflict",
           relations=[("Pessimistic Offline Lock", "pattern-pessimistic-offline-lock"), ("Concurrency", "ch05-concurrency")],
           lab=OFF, demo="optimistic_offline_lock",
           snippet="""
UPDATE leases SET status = ?, version = version + 1
WHERE id = ? AND version = ?
            """,
           tasks=["أعد إنتاج الفشل من جلستين.", "أظهر رسالة تعيد تحميل الحالة.", "أضف الإصدار في حالة العميل."],
           questions=[("شرط الـ WHERE؟", "المفتاح والإصدار المتوقع."), ("لو rowcount صفر؟", "شخص تاني سبقك."), ("بيقفل الصف طول التحرير؟", "لا. يكتشف عند الكتابة."), ("المعمل يفشل أنهي حفظ؟", "التاني بإصدار 0.")]),
        _s(id="pattern-pessimistic-offline-lock", nav="Pessimistic Offline Lock", group="الجزء ٢ · أقفال أوفلاين", title="Pessimistic Offline Lock", subtitle="الجلسة الأولى تملك العقد", icon="🔒", tone="coral",
           intent="قبل التحرير تسجّل مالكًا في جدول أقفال. جلسة تانية تشوف المالك وترفض. لازم مهلة انتهاء لأن المستخدم قد ي disappearance.",
           use=["ما ينفعش مستخدمان يعدّلان نفس العقد معًا.", "تعارض غالي زي صرف دفعة."],
           avoid=["قفل بلا انتهاء.", "قفل كل النظام بقفل واحد."],
           diagram="session-a owns lease 1\nsession-b → Locked",
           relations=[("Optimistic Offline Lock", "pattern-optimistic-offline-lock"), ("Coarse-Grained Lock", "pattern-coarse-grained-lock")],
           lab=OFF, demo="pessimistic_offline_lock",
           snippet="if row and row['owner'] != owner: raise Locked(...)",
           tasks=["أضف وقت انتهاء وارفض القفل المنتهي.", "حرّر القفل عند الحفظ.", "قارن تجربة المستخدم مع الإصدار."],
           questions=[("إمتى الرفض؟", "قبل التحرير، لما المالك مختلف."), ("ليه الانتهاء؟", "عشان القفل المهجور ما يجمّدش العقد."), ("فين يتخزن؟", "جدول أقفال أو عمود مالك."), ("المعمل: مين المالك؟", "session-a، و session-b تُرفض.")]),
        _s(id="pattern-coarse-grained-lock", nav="Coarse-Grained Lock", group="الجزء ٢ · أقفال أوفلاين", title="Coarse-Grained Lock", subtitle="قفل العقد يغطي بنوده", icon="🧺", tone="coral",
           intent="بدل قفل كل بند، اقفل جذر العقد. البنود تتعدل تحت نفس المالك. يقلل عدد الأقفال ويمنع تعديل بند والعقد مقفول عند غيرك.",
           use=["بيان فيه أجزاء تابعة زي البنود.", "تحب قفلًا واحدًا للمجموعة."],
           avoid=["جذر ضخم يقفل أجزاء ما بتتعدلش مع بعض.", "قفل خشن على جداول غير مرتبطة."],
           diagram="lock(lease 1) covers line 1 and line 2",
           relations=[("Pessimistic Offline Lock", "pattern-pessimistic-offline-lock"), ("Dependent Mapping", "pattern-dependent-mapping")],
           lab=OFF, demo="coarse_grained_lock",
           snippet="acquire(conn, 'session-a', 1)  # lines ride along",
           tasks=["ارفض تعديل بند لو جذره مقفول لمستخدم آخر.", "ارسم حدود البيان: عقد وبنود فقط.", "اشرح حالة قفل خشن زايد."],
           questions=[("بتقفل إيه؟", "الجذر."), ("البنود ليها صف قفل؟", "مش لازم. تغطيتها من الأب."), ("الخطر؟", "تعطيل أجزاء ما كانش لازم تقفل."), ("المعمل يغطي أنهي بنود؟", "1 و 2.")]),
        _s(id="pattern-implicit-lock", nav="Implicit Lock", group="الجزء ٢ · أقفال أوفلاين", title="Implicit Lock", subtitle="المابر يقفل وأنت تغيّر الحالة", icon="🙈", tone="coral",
           intent="مستدعي change_status ما يطلبش القفل بنفسه. المحرّر ياخد القفل المتشائم ثم الحفظ بالإصدار. القفل ما يتنسيش لأن المكان الوحيد للتعديل يعمل كده.",
           use=["كل الكتابات تمر من بوابة واحدة.", "عايز ضمان إن مفيش مسار يعدّل من غير قفل."],
           avoid=["مسار كتابة جانبي يلتف على المحرّر.", "إخفاء القفل لدرجة إن الفشل ما يفهموش حد."],
           diagram="editor.change_status → acquire → save_with_version",
           relations=[("Pessimistic Offline Lock", "pattern-pessimistic-offline-lock"), ("Optimistic Offline Lock", "pattern-optimistic-offline-lock"), ("Unit of Work", "pattern-unit-of-work")],
           lab=OFF, demo="implicit_lock",
           snippet="acquire(...); save_with_version(...)",
           tasks=["أضف مسارًا ثانيًا وخلّيه يستخدم نفس المحرّر.", "أظهر خطأ واضح لو القفل مرفوض.", "اكتب ليه الإخفاء مش عذر لتخطي الخدمة."],
           questions=[("ضمني يعني إيه؟", "القفل داخل البنية مش في كل مستدعٍ."), ("إيه اللي المعمل بيجمعه؟", "قفل متشائم ثم حفظ بإصدار."), ("لو في كتابة مباشرة SQL؟", "تكسر الضمان."), ("المالك النهائي؟", "session-a والحالة billed.")]),
        _s(id="ch17-session", nav="Ch.17 Session state", group="الجزء ٢ · حالة الجلسة", title="Session State Patterns", subtitle="عميل، ذاكرة خادم، أو جدول", icon="🧭", tone="teal",
           intent="ثلاث أماكن لحالة المعالج: ترجع مع الطلب، تقعد في ذاكرة الخادم، أو صف في قاعدة.",
           use=["معالج أطول من طلب.", "اختيار مكان يناسب عدد العقد."],
           avoid=["كائن دومين حي داخل الجلسة.", "حالة خادم محلية مع عدة عقد من غير مشاركة."],
           diagram="client fields | server map | sessions table",
           relations=[("Client Session State", "pattern-client-session-state"), ("Server Session State", "pattern-server-session-state"), ("Database Session State", "pattern-database-session-state")],
           lab=SESS, demo="server_session_state", snippet="_SERVER['sess-7']['step'] = 'confirm'",
           tasks=["خزّن خطوة المعالج في الأماكن الثلاثة.", "اكتب إيه اللي يضيع لو العملية وقعت."],
           questions=[("أنهي مكان يعيد التشغيل؟", "العميل والقاعدة. الذاكرة لأ."), ("أنهي مكان يسهل التلاعب؟", "العميل، لو من غير توقيع."), ("أنهي مكان يحمّل القاعدة؟", "Database Session State."), ("الحالة دومين؟", "لا. بيانات محادثة.")]),
        _s(id="pattern-client-session-state", nav="Client Session State", group="الجزء ٢ · حالة الجلسة", title="Client Session State", subtitle="الخطوة ترجع في الطلب الجاي", icon="📨", tone="teal",
           intent="الخادم ما يحتفظش بالمعالج. الحقول المخفية أو الرمز ترجع مع الإرسال التالي. يناسب خوادم كثيرة، بشرط التحقق لأن العميل يقدر يغيّر القيم.",
           use=["مقياس أفقي من غير جلسة مشتركة.", "خطوات قليلة وبيانات صغيرة."],
           avoid=["بيانات سرية بلا تشفير.", "حالة ضخمة في كل طلب."],
           diagram="hidden step=confirm → post → step=done",
           relations=[("Server Session State", "pattern-server-session-state"), ("Application Controller", "pattern-application-controller")],
           lab=SESS, demo="client_session_state",
           snippet="posted = dict(hidden); posted['step'] = 'done'",
           tasks=["وقّع الحقول أو أعد فحص العقد من القاعدة.", "ارفض خطوة لا تأتي بعد الحالية.", "قارن حجم الطلب مع جلسة خادم."],
           questions=[("مين يخزن؟", "العميل بين الطلبات."), ("الخطر؟", "العبث."), ("الميزة؟", "الخادم بلا حالة."), ("المعمل يغيّر الخطوة لإيه؟", "done.")]),
        _s(id="pattern-server-session-state", nav="Server Session State", group="الجزء ٢ · حالة الجلسة", title="Server Session State", subtitle="معرّف جلسة يفتح خريطة في الذاكرة", icon="🖥️", tone="teal",
           intent="المتصفح يرسل معرفًا فقط. الخادم يحتفظ بالخطوة والأصل المختار في قاموس. سريع، ويضيع مع إعادة التشغيل، ويحتاج تثبيت الجلسة أو مخزنًا مشتركًا لو الخوادم متعددة.",
           use=["حالة متوسطة الحجم على خادم واحد أو مخزن مشترك.", "بيانات ما تحبش ترجّعها للعميل."],
           avoid=["جلسة محلية خلف موازن دائري من غير لصق.", "تخزين اتصالات مفتوحة داخل القاموس."],
           diagram="sess-7 → {lease_id, step}",
           relations=[("Client Session State", "pattern-client-session-state"), ("Database Session State", "pattern-database-session-state")],
           lab=SESS, demo="server_session_state",
           snippet="_SERVER['sess-7'] = {'lease_id': 1, 'step': 'choose_asset'}",
           tasks=["انقل القاموس إلى مخزن تقدر تمسحه بانتهاء.", "اكتب إيه اللي يحصل بعد إعادة تشغيل العملية.", "قارن مع جدول sessions."],
           questions=[("إيه اللي عند العميل؟", "المعرف فقط."), ("ليه سريع؟", "القراءة من الذاكرة."), ("ليه هش؟", "الذاكرة مش متينة ولا مشتركة تلقائيًا."), ("الخطوة النهائية في المعمل؟", "confirm.")]),
        _s(id="pattern-database-session-state", nav="Database Session State", group="الجزء ٢ · حالة الجلسة", title="Database Session State", subtitle="صف في جدول sessions", icon="🗄️", tone="teal",
           intent="نفس حمولة الجلسة تتخزن في قاعدة. تعيش إعادة التشغيل وتتشارك بين الخوادم. كل طلب يدفع ثمن قراءة أو كتابة.",
           use=["عدة عقد من غير لصق جلسة في الذاكرة.", "حالة لازم تبقى بعد التعطل."],
           avoid=["كتابة القاعدة لكل نقرة والبيانات صغيرة وتنفع عند العميل.", "تخزين أسرار بلا داعي."],
           diagram="sessions(id, payload json)",
           relations=[("Server Session State", "pattern-server-session-state"), ("Serialized LOB", "pattern-serialized-lob")],
           lab=SESS, demo="database_session_state",
           snippet="INSERT INTO sessions (id, payload) VALUES ('sess-7', json)",
           tasks=["حدّث الخطوة في الصف.", "أضف انتهاء صلاحية وامسح القديم.", "قارن عدد الكتابات مع حالة العميل."],
           questions=[("المكسب؟", "بقاء ومشاركة."), ("التمن؟", "ضغط على القاعدة."), ("الحمولة في المعمل؟", "JSON فيه lease_id و step."), ("فرقه عن حالة العمل؟", "دي محادثة مش صف العقد نفسه.")]),
        _s(id="ch18-base", nav="Ch.18 Base", group="الجزء ٢ · أنماط أساس", title="Base Patterns", subtitle="قطع صغيرة تتكرر تحت باقي الأنماط", icon="🧱", tone="purple",
           intent="أنماط أساس: بوابة، مابر، أب طبقة، واجهة منفصلة، سجل، قيمة، مال، حالة خاصة، إضافة، بديل خدمة، ومجموعة سجلات.",
           use=["لما تسمي قطعة صغيرة في التصميم بدل ما تعيد شرحها.", "مراجعة فصل الختام بعد الأنماط الكبيرة."],
           avoid=["استخدام Registry كمخزن عام لكل شيء.", "Special Case يخبي خطأ برمجيًا حقيقيًا."],
           diagram="Gateway · Mapper · Layer Supertype\nValue · Money · Special Case\nPlugin · Stub · Record Set",
           relations=[("Gateway", "pattern-gateway"), ("Money", "pattern-money"), ("Separated Interface", "pattern-separated-interface")],
           lab=BASE, demo="money", snippet="Money(50000) + Money(20000) * 2",
           tasks=["سمِّ ثلاثة أنماط أساس ظهرت في قصة الإيجار.", "استبدل None عميل بـ Special Case."],
           questions=[("ليهه أنماط أساس؟", "لأنها تتكرر داخل الأنماط الأكبر."), ("Money قيمة ولا كيان؟", "قيمة."), ("Registry خطره؟", "اعتماد مخفي وصعب الاختبار."), ("Record Set بيدخل فين؟", "Table Module غالبًا.")]),
        _s(id="pattern-gateway", nav="Gateway", group="الجزء ٢ · أنماط أساس", title="Gateway", subtitle="واجهة ضيقة فوق خدمة أسعار خارجية", icon="🚪", tone="purple",
           intent="النظام الخارجي شكله غريب. البوابة تقدّم دالة واحدة: هات السعر الشهري بالسنت. الدومين ما يعرفش تفاصيل المصدر.",
           use=["API خارجي أو مكتبة مزعجة.", "عايز تستبدل المصدر في الاختبار."],
           avoid=["بوابة فيها قواعد الخصم.", "تمرير أنواع المكتبة الخارجية لباقي النظام."],
           diagram="domain → RateGateway.monthly_rate_cents → outside table",
           relations=[("Separated Interface", "pattern-separated-interface"), ("Service Stub", "pattern-service-stub"), ("Table Data Gateway", "pattern-table-data-gateway")],
           lab=BASE, demo="gateway", snippet="return table[asset_name]",
           tasks=["أضف أصلًا في الجدول الخارجي فقط واترك Lease كما هو.", "استبدل البوابة ببديل اختبار.", "اكتب الفرق عن Table Data Gateway."],
           questions=[("بتغلّف إيه؟", "واجهة خارجية."), ("Table Data Gateway حالة خاصة؟", "نعم، لجدول قاعدة."), ("المعمل يرجع كام للشاحنة؟", "50000 سنت."), ("ليهه مش في الدومين؟", "عشان شكل المصدر يتغير لوحده.")]),
        _s(id="pattern-mapper", nav="Mapper", group="الجزء ٢ · أنماط أساس", title="Mapper", subtitle="ترجمة بين شكلين من غير ما يتغيرا معًا", icon="🔀", tone="purple",
           intent="كائن أو قاموس يحوّل صفًا إلى شكل دومين. Data Mapper هو الأشهر، والنمط العام أي ترجمة بين تمثيلين مستقلين.",
           use=["شكل جدول غير شكل الدومين.", "طبقة تكامل بين نظامين."],
           avoid=["نسخ حقول من غير فرق حقيقي بين الشكلين.", "منطق عمل أثناء النسخ."],
           diagram="{id, status} → {lease_id, state}",
           relations=[("Data Mapper", "pattern-data-mapper"), ("Metadata Mapping", "pattern-metadata-mapping")],
           lab=BASE, demo="mapper", snippet="domain = {'lease_id': row['id'], 'state': row['status']}",
           tasks=["أضف حقلًا يتغير اسمه فقط في المابر.", "ارفض وضع خصم أثناء الترجمة.", "اربط المثال بـ LeaseMapper."],
           questions=[("المابر دومين؟", "لا. مترجم."), ("Data Mapper أخص؟", "نعم، بين كائن وقاعدة."), ("المعمل يغيّر الأسماء لإيه؟", "lease_id و state."), ("فين القواعد؟", "بعد الترجمة، على الكائن.")]),
        _s(id="pattern-layer-supertype", nav="Layer Supertype", group="الجزء ٢ · أنماط أساس", title="Layer Supertype", subtitle="أب مشترك لكل كائنات الدومين", icon="🧱", tone="purple",
           intent="DomainObject يحمل id. Lease يرثه. السلوك المشترك للطبقة في الأب، مش منسوخ في كل كيان.",
           use=["حقول أو مساعدات فعلًا مشتركة.", "هوية موحدة للكائنات المحفوظة."],
           avoid=["أب إلهي فيه كل شيء.", "وراثة عشان تشارك دالة واحدة كانت وحدة حرة أنسب."],
           diagram="DomainObject(id)\n   NamedLease(status)",
           relations=[("Identity Field", "pattern-identity-field"), ("Separated Interface", "pattern-separated-interface")],
           lab=BASE, demo="layer_supertype", snippet="@dataclass\nclass DomainObject:\n    id: int | None = None",
           tasks=["أضف طابع وقت على الأب واستخدمه من عقد وأصل.", "انقل دالة تخص الفوترة فقط إلى Lease.", "اكتب علامة الأب المتخم."],
           questions=[("الأب فيه قواعد الإيجار؟", "لا. المشترك فقط."), ("المعمل يثبت إيه؟", "إن NamedLease هو DomainObject ومعاه id."), ("بديل الوراثة؟", "تركيب أداة صغيرة."), ("علاقته بـ Identity Field؟", "الأب مكان طبيعي لحمل المفتاح.")]),
        _s(id="pattern-separated-interface", nav="Separated Interface", group="الجزء ٢ · أنماط أساس", title="Separated Interface", subtitle="BillingPort في الدومين والتنفيذ في SQLite", icon="🔌", tone="purple",
           intent="الدومين يعرّف charge. التنفيذ الفعلي يكتب الفاتورة. تقدر تختبر الدومين ببديل. الاعتماد على الواجهة مش على sqlite.",
           use=["طبقة ما تحبش تعتمد على تفصيلة تحتها.", "أكتر من تنفيذ: قاعدة وبديل."],
           avoid=["واجهة لكل دالة من غير ما في بديل أو حد.", "واجهة في نفس الملف مع SQL وتسميها فصلًا."],
           diagram="BillingPort.charge\n   SqliteBilling | BillingStub",
           relations=[("Service Stub", "pattern-service-stub"), ("Plugin", "pattern-plugin"), ("Gateway", "pattern-gateway")],
           lab=BASE, demo="separated_interface",
           snippet="""
class BillingPort(ABC):
    def charge(self, lease_id, amount) -> str: ...
            """,
           tasks=["مرّر المنفذ للخدمة مش الاتصال.", "نفّذ المنفذ بذاكرة.", "اكتب اعتمادًا ممنوعًا: الدومين يستورد sqlite3."],
           questions=[("الواجهة فين؟", "عند المستدعي، التنفيذ عند التفصيلة."), ("المعمل أي تنفيذ يستخدم؟", "SqliteBilling ويرجع stored."), ("ليه ABC؟", "عشان العقد واضح في بايثون."), ("علاقته بـ Dependency Inversion؟", "نفس الفكرة: العالي ما يعتمدش على الواطي مباشرة.")]),
        _s(id="pattern-registry", nav="Registry", group="الجزء ٢ · أنماط أساس", title="Registry", subtitle="مكان تجد منه البوابة — واستخدمه قليلًا", icon="📍", tone="purple",
           intent="سجل عام أو كائن تمرره يجد RateGateway بالاسم. سهل الوصول ومغري يخبي الاعتمادات. المعمل يوضحه كخدمة أسعار، والاختبار أنضف لو مرّرت البوابة صراحة.",
           use=["كائن واسع الحاجة وما تحبش تمرره في كل دالة مؤقتًا.", "إعدادات عملية واحدة."],
           avoid=["سجل عالمي فيه دومين واتصال وثوابت.", "اعتماد مخفي يصعّب الاختبار."],
           diagram="registry.put('rates', gateway)\nregistry.get('rates')",
           relations=[("Gateway", "pattern-gateway"), ("Separated Interface", "pattern-separated-interface")],
           lab=BASE, demo="registry", snippet="reg.put('rates', RateGateway())",
           tasks=["استبدل السجل بمعامل صريح وقارن التوقيع.", "اكتب اختبارًا يكسر بسبب حالة عامة متبقية.", "سجّل بديلًا تحت نفس الاسم."],
           questions=[("بيحل إيه؟", "كيف أجد الخدمة."), ("الثمن؟", "اقتران مخفي."), ("المعمل يجيب سعر إيه؟", "الرافعة 20000."), ("بديل أفضل غالبًا؟", "تمرير الواجهة في المُنشئ.")]),
        _s(id="pattern-value-object", nav="Value Object", group="الجزء ٢ · أنماط أساس", title="Value Object", subtitle="المدى يتساوى بقيمته", icon="💎", tone="purple",
           intent="DateRange يتحدد ببداية ونهاية. نسختان بنفس التواريخ متساويتان. مفيش id. تغييره يعني قيمة جديدة مش تعديل هوية.",
           use=["تاريخ، مال، مدى.", "مفاتيح منطقية من غير جدول."],
           avoid=["كيان عقد له حياة وتتبع. ده مش قيمة.", "قيمة قابلة للتعديل في المكان تخدع المشاركين."],
           diagram="DateRange('2026-01-01','2026-01-31') == same dates",
           relations=[("Money", "pattern-money"), ("Embedded Value", "pattern-embedded-value")],
           lab=BASE, demo="value_object", snippet="@dataclass(frozen=True)\nclass DateRange:\n    start: str\n    end: str",
           tasks=["أضف تداخل مدى مع مدى العقد.", "ارفض تعديل الحقل بعد البناء.", "قارن مع Lease اللي له id."],
           questions=[("المساواة على إيه؟", "القيم."), ("ليه frozen؟", "عشان ما تتغيرش من ورا اللي ممسكها."), ("ليه من غير id؟", "ما لهاش صف وهوية تتبع."), ("المعمل يثبت التضمين؟", "إن يوم ١٥ داخل يناير.")]),
        _s(id="pattern-money", nav="Money", group="الجزء ٢ · أنماط أساس", title="Money", subtitle="سنت وعملة وحساب يرفض الخلط", icon="💰", tone="purple",
           intent="المبلغ عدد صحيح من السنت مع عملة. الجمع والضرب محليان. خلط عملة غير مدعومة يرفض. هذا أساس القسط 900 دولار في كل المعامل.",
           use=["أي مبلغ في الفواتير والعقود.", "تجنب float."],
           avoid=["float للدولار.", "جمع عملات من غير تحويل صريح."],
           diagram="Money(50000) + Money(20000) * 2 = USD 900.00",
           relations=[("Value Object", "pattern-value-object"), ("Embedded Value", "pattern-embedded-value"), ("Domain Model", "pattern-domain-model")],
           lab=BASE, demo="money", snippet="total = Money(50000) + Money(20000) * 2",
           tasks=["أضف خصمًا يرجع Money جديدة.", "ارفض عملة EUR في البناء.", "خزّن الناتج بعمودين عبر Embedded Value."],
           questions=[("ليه سنت؟", "عشان من غير كسور ثنائية."), ("ناتج المعمل؟", "USD 900.00 ثم رفض EUR."), ("قيمة ولا كيان؟", "قيمة."), ("فين تتخزن؟", "أعمدة المالك أو حساب في الذاكرة فقط.")]),
        _s(id="pattern-special-case", nav="Special Case", group="الجزء ٢ · أنماط أساس", title="Special Case", subtitle="عميل مجهول بدل None", icon="🕳️", tone="purple",
           intent="بدل ما كل مستدعٍ يفحص None، MissingCustomer عنده اسم افتراضي ودالة label. الكود يتكلم مع عميل دائمًا. لا تستخدمه لإخفاء خطأ مفتاح غلط لازم يتبلغ.",
           use=["غياب متوقع زي عميل محذوف.", "تبسيط واجهة المستدعي."],
           avoid=["تحويل استثناء برمجي إلى حالة صامتة.", "حالة خاصة فيها سلوك يخصم فلوس بالسر."],
           diagram="row is None → MissingCustomer.label()",
           relations=[("Value Object", "pattern-value-object"), ("Foreign Key Mapping", "pattern-foreign-key-mapping")],
           lab=BASE, demo="special_case", snippet="customer = MissingCustomer() if row is None else row",
           tasks=["أضف Special Case لأصل محذوف على بند.", "ميّز خطأ المفتاح عن الغياب المتوقع في رسالة.", "اكتب فرع if None القديم وقارن الطول."],
           questions=[("بديل لإيه؟", "لفحص None المتكرر."), ("المعمل يطبع إيه؟", "Unknown customer."), ("إمتى غلط؟", "لما الغياب خطأ لازم يوقف العملية."), ("علاقته بـ Null Object؟", "نفس الفكرة باسم النمط في الكتاب.")]),
        _s(id="pattern-plugin", nav="Plugin", group="الجزء ٢ · أنماط أساس", title="Plugin", subtitle="اختر سياسة الفوترة بالاسم", icon="🧩", tone="purple",
           intent="السياسات (نسبي أو ثابت) مسجّلة بالاسم. التكوين يختار الكلاس. النواة ما تستوردش كل السياسات لو الربط بالاسم عند الإقلاع.",
           use=["سلوك يتبدل حسب النشر.", "إضافات طرف ثالث على واجهة مستقرة."],
           avoid=["إضافة لكل شرط if كان يكفي.", "تحميل إضافة من مصدر غير موثوق من غير مراجعة."],
           diagram="PLUGINS['prorate'] → ProratePlugin",
           relations=[("Separated Interface", "pattern-separated-interface"), ("Registry", "pattern-registry")],
           lab=BASE, demo="plugin", snippet="chosen = PLUGINS['prorate']()",
           tasks=["أضف سياسة flat وشغّلها من الاسم.", "ارفض اسمًا غير مسجّل.", "خلّي الخدمة تعتمد على الواجهة الناتجة."],
           questions=[("إمتى مش if؟", "لما الاختيار خارج الكود الثابت، من إعداد."), ("المعمل يختار إيه؟", "prorate."), ("الخطر؟", "ربط بالأسماء وأخطاء إملاء."), ("فرقه عن Strategy؟", "Strategy خيار كائن. Plugin يركّز على التحميل والتكوين.")]),
        _s(id="pattern-service-stub", nav="Service Stub", group="الجزء ٢ · أنماط أساس", title="Service Stub", subtitle="فوترة وهمية تسجّل النداء", icon="🧪", tone="purple",
           intent="في الاختبار ما تحبش تكتب فاتورة حقيقية. BillingStub ينفّذ نفس المنفذ ويحفظ النداءات ويرجع stub-ok. التجربة سريعة ومن غير آثار.",
           use=["اختبار خدمة تعتمد على فوترة خارجية.", "تطوير والطرف الآخر مش جاهز."],
           avoid=["تشغيل البديل في الإنتاج بالخطأ.", "بديل يتساهل مع مبلغ سالب والإنتاج يرفض."],
           diagram="BillingService → BillingStub.charge → calls list",
           relations=[("Separated Interface", "pattern-separated-interface"), ("Gateway", "pattern-gateway")],
           lab=BASE, demo="service_stub", snippet="stub.charge(1, Money(90000))",
           tasks=["اختبر الخدمة وتأكد إن النداء اتسجل.", "أضف وضع فشل في البديل.", "امنع البديل من مسار الإنتاج بإعداد صريح."],
           questions=[("البديل تنفيذ لإيه؟", "لنفس واجهة الفوترة."), ("المعمل يثبت إيه؟", "الرجوع stub-ok وتسجيل 90000."), ("فرقه عن قاعدة اختبار؟", "من غير جداول."), ("خطر الإنتاج؟", "نجاح وهمي.")]),
        _s(id="pattern-record-set", nav="Record Set", group="الجزء ٢ · أنماط أساس", title="Record Set", subtitle="مجموعة صفوف تمر إلى وحدة الجدول", icon="📋", tone="purple",
           intent="نتيجة الاستعلام قائمة قواميس: أصل وكمية. Table Module يشتغل عليها. النمط يناسب واجهات وقواعد بتتبادل جداول في الذاكرة مش كائنات غنية.",
           use=["تقارير وشاشات جدولية.", "مدخل Table Module."],
           avoid=["تمرير المجموعة للواجهة وفيها اتصال مفتوح.", "معاملة الصف ككيان عقد غني بالسلوك."],
           diagram="SELECT lines → list[dict] → sum quantity",
           relations=[("Table Module", "pattern-table-module"), ("Table Data Gateway", "pattern-table-data-gateway")],
           lab=BASE, demo="record_set", snippet="record_set = [dict(r) for r in rows]",
           tasks=["مرّر المجموعة إلى LeaseTable.", "أضف صفًا واحسب الكمية.", "اكتب إمتى تحوّلها إلى LeaseLine objects."],
           questions=[("إيه المحتوى في المعمل؟", "بندين وكميات 1 و 2 والمجموع 3."), ("مين يستهلكها غالبًا؟", "Table Module."), ("فيها سلوك؟", "لا. بيانات."), ("فرقه عن Identity Map؟", "مجموعة صفوف مش ضمان كائن فريد.")]),
    ]
