# Generated by Django 5.2.18 on 2026-10-08 14:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProjection",
            fields=[
                ("customer_id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=254)),
                ("display_name", models.CharField(max_length=200)),
                ("aggregate_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "customer_projections",
            },
        ),
        migrations.CreateModel(
            name="PaymentProjection",
            fields=[
                ("order_id", models.UUIDField(primary_key=True, serialize=False)),
                ("outcome", models.CharField(max_length=16)),
                ("payment_reference", models.CharField(blank=True, default="", max_length=128)),
                ("amount_minor", models.BigIntegerField(null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("reason_code", models.CharField(blank=True, default="", max_length=32)),
                ("aggregate_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "payment_projections",
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("aggregate_id", models.UUIDField()),
                ("processed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "processed_events",
            },
        ),
        migrations.CreateModel(
            name="InventoryProjection",
            fields=[
                ("product_id", models.UUIDField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=64)),
                ("quantity_on_hand", models.IntegerField()),
                ("quantity_reserved", models.IntegerField()),
                ("warehouse_code", models.CharField(max_length=64)),
                ("aggregate_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inventory_projections",
                "indexes": [models.Index(fields=["occurred_at", "product_id"], name="ix_inventory_proj_cursor")],
            },
        ),
        migrations.CreateModel(
            name="OrderProjection",
            fields=[
                ("order_id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("customer_id", models.UUIDField(null=True)),
                ("status", models.CharField(max_length=32)),
                ("total_amount_minor", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="", max_length=3)),
                ("cancel_reason", models.CharField(blank=True, default="", max_length=64)),
                ("tracking_reference", models.CharField(blank=True, max_length=128, null=True)),
                ("aggregate_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "order_projections",
                "indexes": [
                    models.Index(fields=["occurred_at", "order_id"], name="ix_order_proj_cursor"),
                    models.Index(fields=["status"], name="ix_order_proj_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductProjection",
            fields=[
                ("product_id", models.UUIDField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("unit_price_amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("active", models.BooleanField()),
                ("aggregate_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "product_projections",
                "indexes": [models.Index(fields=["occurred_at", "product_id"], name="ix_product_proj_cursor")],
            },
        ),
        migrations.CreateModel(
            name="ProjectionVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("aggregate_type", models.CharField(max_length=32)),
                ("aggregate_id", models.UUIDField()),
                ("aggregate_version", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "projection_versions",
                "constraints": [
                    models.UniqueConstraint(fields=("aggregate_type", "aggregate_id"), name="uq_projection_version"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItemProjection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField()),
                ("product_id", models.UUIDField()),
                ("sku", models.CharField(max_length=64)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projections.orderprojection",
                    ),
                ),
            ],
            options={
                "db_table": "order_item_projections",
                "constraints": [models.UniqueConstraint(fields=("order", "position"), name="uq_order_item_position")],
            },
        ),
    ]
